# Generated by Django 2.2.28 on 2023-07-01 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_token_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='uid',
            field=models.CharField(default=None, max_length=40),
            preserve_default=False,
        ),
    ]
