# Generated by Django 2.2.28 on 2023-07-01 05:07

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_token_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='uid',
            field=models.CharField(default=uuid.UUID('1b1823e4-6cc8-4877-bd21-aa80ecc820ea'), max_length=40),
        ),
    ]
